### ISSUE TITLE
Driver Loading Issue 

### ISSUE THREAD

**Issue by michaelalcorn** [PoPGRI/Race#10]
I am having a bug when trying to run the GRAIC Docker Container (step 2 on website). Whenever I run it, I receive an error that the driver is not loaded. In Software and Updates, I have made sure that I am using the NVIDIA Driver. CARLA works on its own when not in the docker container but when running the docker command, I receive the issue. I have followed the steps shown to install Docker CE, NVIDIA-Docker 2, as well as the latest source code / map and tried running the command with sudo. 

![driver_issue](https://user-images.githubusercontent.com/59780950/112036977-a09bb600-8b17-11eb-95b1-a814df7e910a.png)

**Comment by pricejiang** [comment]
@michaelalcorn Hi, thanks for your interest in GRAIC! 
Could you run `docker images` and share the output with us? 
Also, we have created a new docker image as the environment for running GRAIC: 
https://hub.docker.com/r/pricejiang/graic 
You may also try to use this new image which is 10G smaller than the previous one.

**Comment by michaelalcorn** [comment]
Yes! Here is the output of docker images. 
![docker_images](https://user-images.githubusercontent.com/59780950/112546627-0a25f980-8d90-11eb-8117-ae66e48be073.png)
I will try the new image as well!

**Comment by pricejiang** [comment]
Thanks for your reply. Could you run ` sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi` and share us with the output?

**Comment by michaelalcorn** [comment]
Yes! Sorry for late response
![sudo_docker](https://user-images.githubusercontent.com/59780950/113519325-79060e00-9559-11eb-801a-32e1130dac61.png)

**Comment by sundw2014** [comment]
Hi @michaelalcorn, it seems your Nvidia driver is not working. You can run ```lsmod | grep nvidia``` to see if the driver is correctly loaded. If it is, you should see something like this
```
chardorn@indyauto:~$ lsmod | grep nvidia
nvidia_uvm            925696  0
nvidia_drm             45056  3
nvidia_modeset       1114112  7 nvidia_drm
nvidia              19935232  290 nvidia_uvm,nvidia_modeset
drm_kms_helper        184320  1 nvidia_drm
drm                   491520  6 drm_kms_helper,nvidia_drm
ipmi_msghandler       102400  2 ipmi_devintf,nvidia
```
If the above command outputs nothing, you can try the following.
1. Reboot the computer.
2. If the reboot does not solve the problem, go to https://www.nvidia.com/Download/index.aspx?lang=en-us and download the driver. Run the downloaded file and reboot the machine.

Please also see https://github.com/NVIDIA/nvidia-docker/issues/1393 for more details.
