### ISSUE TITLE
Ability to install without Docker

### ISSUE THREAD

**Issue by anon8675309** [PoPGRI/Race#18]
As a competitor, I would like to be able to install and use the software without having a cloud account or pulling a Docker image.  Currently, the [documentation](https://popgri.github.io/Race/installation/) only has instructions for an accounts with AWS or Docker.

This will allow me to build and use the software without unnecessary dependencies or expenses.  It may also allow running the software without root privileges, which is something that Docker requires according to your installation documentation.

This is also a step toward automated build testing for each change that is made to Race.

**Comment by yanmiao2** [comment]
Hi,

Currently, all our development process are done in cloud/docker environment. So we do not provide an official support for local installation.

But what you suggested is something interested and we will take that into consideration in the future. Thanks!
