### ISSUE TITLE
Architecture diagram missing

### ISSUE THREAD

**Issue by anon8675309** [PoPGRI/Race#19]
As a potential competitor, I would like to see an architecture diagram so I can understand how all of the components fit together.  This will help competitors understand what code it is it that they need to write, what will be calling my code, and aid in troubleshooting in the event there are any errors (either with the competitor's code or with Race itself).

**Comment by yanmiao2** [comment]
You can check the below for a high-level diagram.  The starting point for you to start coding will be `graic_core/src/baseline.py`. For detailed inputs and output, you could refer to the actual code and our [documentation](https://popgri.github.io/Race/documentation/) online.

<img width="679" alt="Screen Shot 2022-04-18 at 4 29 16 PM" src="https://user-images.githubusercontent.com/48262576/163881308-56380b05-120f-4d9c-8e73-3fd21314fe6c.png">
